language: node_js
node_js: node

script:
    - npm run listdiff
    - npm run lint
    - npm run test
    - npm run build

deploy:
    - provider: npm
      edge: true
      on:
          branch: master
          tags: true