name: CI and CD

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14
            - uses: pnpm/action-setup@v1.2.1
              with:
                  version: 5.18.9
                  run_install: true
            - run: pnpm run listdiff
            - run: pnpm run lint
            - run: pnpm run test
            - run: pnpm run build

    publish-npm:
        needs: build
        if: startsWith(github.ref, 'refs/tags/v')
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14
                  registry-url: https://registry.npmjs.org/
            - uses: pnpm/action-setup@v1.2.1
              with:
                  version: 6.0.0
                  run_install: true
            - run: pnpm run build
            - run: pnpm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

    publish-gpr:
        needs: build
        if: startsWith(github.ref, 'refs/tags/v')
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14
                  registry-url: https://npm.pkg.github.com/
            - uses: pnpm/action-setup@v1.2.1
              with:
                  version: 6.0.0
                  run_install: true
            - run: pnpm run build
            - run: pnpm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
